"use client";
import { Inter } from "next/font/google";
//import "./globals.css";
import Nav from "./nav";
import { ThemeProvider } from "@mui/material/styles";
import theme from "./theme";
import { AuthContext, AuthContextProvider } from "../context/authContext";
import { useContext } from "react";

import { Provider } from "react-redux";
import { store } from "../store/store";

const inter = Inter({ subsets: ["latin"] });

const metadata = {
  title: "NewzZ",
  description: "Generated by Vvv",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <ThemeProvider theme={theme}>
          <Provider store={store}>
            <AuthContextProvider>
              <Nav />
              {children}
            </AuthContextProvider>
          </Provider>
        </ThemeProvider>
      </body>
    </html>
  );
}
